### ISSUE TITLE
!!! Compiling ruby 3.1.2 failed!

### ISSUE THREAD

**Issue by BoOelkers** [rubyonmac/rubyonmac-issues#11]
**In which version of Ruby on Mac did you find the bug?**
Basic, Prime, or Pro?
Prime

**Describe the bug**
I'm not able to install ruby. I've run the reset script and then the `rom` script

**Details about your Mac**
Before you ran the script for the first time, did you already have development tools like Homebrew installed, or did you run it on a fresh and clean macOS?

I am on the latest MacOS 13 Beta. I had issues with ruby so I bought this product to try and help. I ran the reset script and then the `rom` script

**Please attach the Ruby on Mac log file**
[rom-prime.log](https://github.com/rubyonmac/rubyonmac-issues/files/9254143/rom-prime.log)

**Comment by monfresh** [comment]
Hi @BoOelkers. Thanks for buying 
Ruby on Mac! Unfortunately, macOS Beta versions are not supported because Homebrew doesn't support them. 

If you run "brew doctor", you should see a big warning about things not working on macOS 13. 

I tried to make this as clear as possible in the FAQ on the site, in the documentation, and in my blog posts. Perhaps you missed it? If so, do you recommend an additional way to let people know that Ruby on Mac won't work on macOS 13 Beta?

For now, I recommend going back to Monterey, or waiting until Homebrew supports Ventura when it's officially released.

**Comment by BoOelkers** [comment]
Ended up fixing it on my own

**Comment by monfresh** [comment]
Great! Do you mind sharing your solution so I can add it to the docs?
