### ISSUE TITLE
schema.rb file is empty after I run rails db:migrate

### ISSUE THREAD

**Issue by zach28attack** [rubyonmac/rubyonmac-issues#12]
the summary of the problem: I'm trying to create a simple crud project to practice and when I create a table using rails g migration create_articles it creates a migration file. So when I add the code

```
create_table :articles do |t|
 t.string :title
 t.text :description
 t.timestamps
end
```
then run the rails command rails db:migrate a schema file is created, but it is completely empty.

```
ActiveRecord::Schema[7.0].define(version: 2022_08_21_180236) do
  create_table "articles", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end

```

I have : 

- run the script in reset mode multiple times also the code `rom` to reinstall

- I've tried dropping the empty table by generating another migration file and when that gets pushed to the db nothing happens and the table remains

- use rails db:rollback and that works but when I rerun the migration file the problem persists

I bought the Pro version. before I ran the script. I installed rails using home-brew. which lead me to have problems using the rails command, I then caved and bought the script. When first running the script everything was working fine until the rails command wasn't recognized anymore and the old problem resurfaced. I have also posted this question on stack overflow in search of an answer. 

using a m1 MacBook Pro 

 thanks for any help.

edit: also the problem persists across new projects created with command rails new blog or using rails g scaffold Articles to create the migrate files then migrate.

**Comment by monfresh** [comment]
Hi @zach28attack. Thanks for buying Ruby on Mac! It sounds like things are not working the way you expect them to. I'd be happy to help. I think there are 2 separate issues here:

1. For the issue where the rails command is not recognized anymore, I suggest reading the "Post-Installation Guides" in the Ruby on Mac documentation (in the docs.html file). The most common reason for missing commands is because you switched to a directory that doesn't have a `.ruby-version` file, or because rails was not yet installed in the Ruby version that chruby switched to.
2. For the Rails DB issue, that has nothing to do with Ruby on Mac. Help with new or existing Rails apps normally requires upgrading to the "Ultimate" version of Ruby on Mac, but I'd be happy to point you in the right direction.

You say that when the schema file is created, it is completely empty, yet I see you pasted its contents. What exactly do you mean by "empty?" What are you expecting to happen after running `rails db:migrate`? That migration you created will only create an empty Articles table with a "title" and "description" columns, but they won't contain any data at this point.

You can verify that the `articles` table was created by running `bin/rails dbconsole`. Then if you're using the default `sqlite3` DB, you can check by running `.schema articles`. If you're using Postgres, you can check with `\d articles`.

The only thing the schema file shows you is the structure of the DB, not the contents. In other words, if you create a new article with the title "hello" and description "foo", you won't see that in the schema file. You'll need to look inside the DB to see the values that it contains, or use ActiveRecord to look them up.

I recommend following the Rails Getting Started guide here:

https://guides.rubyonrails.org/getting_started.html

In particular, try starting with the [generating a model](https://guides.rubyonrails.org/getting_started.html#mvc-and-you-generating-a-model) section, and then use section 6.3 to create articles in the DB.

When you run `rails g scaffold Articles` followed by `bin/rails db:migrate`, it will create an empty Articles table with only 2 columns: `created_at` and `updated_at`. That's because all tables get those "timestamps" columns by default, but you haven't specified any additional columns in the scaffold command, so there won't be any other columns. 

If you want to add columns after having run that initial migration, you can't just update the initial migration file and run `rails db:migrate` again. You have to create a new migration that adds those columns to the existing table. Alternatively, you can rollback the initial migration, which should remove the Articles table, then you can update the migration file with the new columns, then migrate again.

For scaffolds, I recommend reading this guide, and search for "scaffold":

https://guides.rubyonrails.org/command_line.html#bin-rails-generate

**Comment by monfresh** [comment]
And I also recommend reading about migrations here: https://guides.rubyonrails.org/active_record_migrations.html

**Comment by zach28attack** [comment]
thank you for responding! I read the relevant sections in the migrations link but I'm still unsure why my schema file doesn't have the columns Title and Description in it when the migration file, before I run any migrations, does. for instance when I go into the rails console and type 

```
irb(main):002:0> article = Article.new
=> #<Article:0x00000001055d0c40 id: nil, created_at: nil, updated_at: nil>
irb(main):003:0> 
```
I don't see the two columns I'm trying to create.

I only suspected the issue was how I ran the script because I haven't seen anyone have this issue online 

thanks again for any help

**Comment by monfresh** [comment]
It's hard for me to help you if I can't see exactly how you're trying to add those columns. Can you paste the exact contents of your migration file, or better yet, can you push your entire Rails project to GitHub and send me a link to it?

Also, what is the output of `rails db:migrate:status`?

**Comment by zach28attack** [comment]
https://github.com/zach28attack/test_app

```
test_app % rails db:migrate:status

database: db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20220821221325  Create articles
```

**Comment by monfresh** [comment]
Now try `rails db:rollback`. What does it say?

Then `rails db:migrate`, and your schema should be updated. If not, do you see any errors in the terminal?

**Comment by monfresh** [comment]
Here's what I did, and you can try too:

1. Create a `playground` directory for testing things: `mkdir ~/playground && cd ~/playground`
2. Clone your repo. I used the GitHub CLI: `gh repo clone zach28attack/test_app`
3. `cd test_app`
4. `bin/setup` - this is the setup file Rails adds by default to new projects

This added the missing columns to the schema.

**Comment by zach28attack** [comment]
```
rails db:migration:status

database: db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20220821221325  Create articles

zacharycasares@Zacharys-MacBook-Pro test_app % rails db:rollback
== 20220821221325 CreateArticles: reverting ===================================
-- drop_table(:articles)
   -> 0.0012s
== 20220821221325 CreateArticles: reverted (0.0037s) ==========================

zacharycasares@Zacharys-MacBook-Pro test_app % rails db:migrate
== 20220821221325 CreateArticles: migrating ===================================
-- create_table(:articles)
   -> 0.0011s
== 20220821221325 CreateArticles: migrated (0.0012s) ==========================

```

this actually fixed the issue in this project but I created a new one to make sure I can replicate the success and the same problem persists. the title and description column are empty with the steps above not making a difference

https://github.com/zach28attack/test_app_2

**Comment by zach28attack** [comment]
test_app_2 % rails db:migrate:status

database: db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20220822042950  Create articles table

**Comment by monfresh** [comment]
When asking for help, it's best to be as explicit as possible. Here's an article I wrote that covers some of the common issues people face when running into coding problems: 

https://www.moncefbelyamani.com/tips-for-debugging-and-asking-for-help/

In this particular case, try writing down step by step everything you did to see if you can spot the problem. Or record a video and explain out loud what you're doing step by step. 

Next, try achieving the same result with different steps. So far, it sounds like you've been performing the same steps each time with each new test app, and using that to convince yourself that something is wrong with Rails or your computer. This is known as confirmation bias.

Instead, try to **disprove** that theory by trying to create the Articles table using a different approach. If you try various ways to disprove the theory, but you're not able to, then that likely means your theory is correct. However, if you are able to disprove it, then it means your theory is wrong. Here's a great example of an experiment that shows how most people naturally only think about confirming their hypotheses instead of trying to contradict them:

https://fs.blog/peter-cathcart-wason-falsification/

Here's how I would try to disprove your theory: immediately after you create a brand new Rails app with `rails new [name of the app]` and `cd` into it, instead of whatever you were doing before, follow the steps in section 6 of the Getting Started with Rails guide exactly as written:

```
bin/rails generate model Article title:string body:text
```
then
```
bin/rails db:migrate
```
then check the contents of your schema:
```
cat db/schema.rb
```
If your `schema.rb` file shows the title and body columns, then that proves that the issue you were seeing before is related to something you did. Compare the two methods and try to figure out which difference is causing the issue.

I hope this helps.

**Comment by zach28attack** [comment]
Honestly thank you so much for spending your time helping me. I understand this was no fault of yours or your script. 

Using `bin/rails generate model Article title:string body:text` to generate the migration file and the columns thru the terminal first before running the migrations file and everything works as it should. I can replicate the success of creating new table with the intended fields.

Thanks you again for your patience  with my problem you were tremendously helpful.

**Comment by monfresh** [comment]
You are very welcome! I'm glad it all worked out. The main thing to understand is that once a migration has been run, you can't make changes to it by modifying the original migration file and running the migration again. You either have to roll it back, then migrate again (if the migration file was already modified), or you have to create a new migration to make changes.

When you're practicing on your own computer, it's fine to roll back, but in production, you have to create a new migration for each change, so it's good to practice that workflow as well.

**Comment by monfresh** [comment]
I also recommend using the [strong_migrations](https://github.com/ankane/strong_migrations) gem to learn more about migrations and so it can automatically detect unsafe migrations.
