### ISSUE TITLE
Compiling ruby 3.1.3 failed, troubleshooting steps don't help

### ISSUE THREAD

**Issue by dimovskidamjan** [rubyonmac/rubyonmac-issues#14]
**In which version of Ruby on Mac did you find the bug?**
Basic

**Describe the bug**
I get an error saying "Compiling ruby 3.1.3 failed!" and I've gone through the troubleshooting section without finding a fix.

**Details about your Mac**
It wasn't a clean install of macOS, but I did all the steps required in the prerequisites step.

**Please attach the Ruby on Mac log file**
[rom-basic.log](https://github.com/rubyonmac/rubyonmac-issues/files/10111786/rom-basic.log)

As I can see, the error occurs here: `ossl_ts.c:829:5: error: incomplete definition of type 'struct TS_verify_ctx'` which doesn't seem like a problem with my setup.

Help appreciated!

**Comment by monfresh** [comment]
Hi @dimovskidamjan. Thanks for buying Ruby on Mac!

The compilation failure is directly caused by the errors reported by Homebrew on your computer. If you look in the Ruby compilation section of the log, you will see several references to `/opt/local`.

The issue is similar to the "Python warnings and config scripts" that's mentioned in the troubleshooting guide. The problem is caused by installing things in locations that conflict with Homebrew. In your case, it looks like you installed things in `/opt/local`, or maybe a tool you used installed things in that location. Did you use MacPorts by any chance? I think they use the `/opt/local` folder. MacPorts and Homebrew are not compatible with one another. Ruby on Mac currently only supports Homebrew. I will update the docs to make that clearer.

Typically, that location will be referenced in your shell file, such as `~/.zshrc` where you might be adding `/opt/local` to your `PATH`. So, the solution would be to remove or disable any lines that reference `/opt/local`. You can give that a try, but I'm not sure if that will be enough to solve the compilation errors. If it doesn't work, the guaranteed way to solve all issues is to start over from scratch.

I hope this helps!

**Comment by dimovskidamjan** [comment]
@monfresh I see what you mean, however there are no lines in my `~/.zshrc` file that I use which reference `opt/local` at all. When you say start over from scratch, what exactly do you mean?

**Comment by monfresh** [comment]
If you run `echo $PATH` in your terminal, you will see that `/opt/local` is included in the PATH. The only way that can happen is if something is adding that location to your PATH. Other places where this might happen are:
~/.zlogin
~/.zprofile
~/.bash_profile
~/.profile
~/.bashrc

One way to test if it's specific to your zsh shell is to try switching to bash temporarily:

```
chsh -s /bin/bash
```
Then open a new terminal tab (or quit and restart), then run `echo $PATH` and see if `/opt/local` is still included. If not, then it's one of the zsh shell files that is adding `/opt/local`. If you still see `/opt/local` in bash, then it might be set in one of the bash shell files I listed above.

To switch back to zsh:
```
chsh -s /bin/zsh
```
and quit and restart your terminal.

The `/opt/local` folder does not exist on a brand new Mac, so the only way it got created is if you installed something there directly or if you installed some program that installed things there. Can you think of anything?

By start over from scratch, I mean follow the instructions in the Troubleshooting guide in the section called "Start over from scratch". If you don't know what is using `/opt/local`, you can try backing it up somewhere, and then deleting everything in there instead of doing the entire "start over from scratch" procedure.

**Comment by dimovskidamjan** [comment]
You were right @monfresh, it was MacPorts. I don't know how or why I missed it before, but it was clearly stated in the profile file that MacPorts has added /opt/local to the path. Once I got rid of that, rubyonmac did it's job perfectly. I still have some leftover junk from all of my failed attempts at fixing ruby, so I think I'm going to take a look at the "Start from scratch" part anyway, just so I'm certain that everything is nice and tidy. Thanks for the support, and thanks for the awesome software!

**Comment by monfresh** [comment]
You're welcome! I'm glad you got it working. Happy New Year!
