### ISSUE TITLE
An error occurred while installing nio4r

### ISSUE THREAD

**Issue by regiomag** [rubyonmac/rubyonmac-issues#17]
Hello,

I did buy rubyonmac unlimited, i did try different time to run in reset mode but I am not able to make my app work on my M1.

Here is my machine specs
My github : regiomag
Apple M1 Max
arm64
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false

I am having a rails project running on ruby 2.6.10 (we will upgrade it, promised..) and rails 5.0.0 

I was able to install through rubyonmac the complete install with chruby and could install ruby 2.6.10. 

When I do bundle install, I am getting the following error : 

An error occurred while installing nio4r (1.2.1), and Bundler cannot continue.
Make sure that `gem install nio4r -v '1.2.1'` succeeds before bundling.

Any clue ? 

you’ll find all logs file attached. 

Thank you and best regards
[log.zip](https://github.com/rubyonmac/rubyonmac-issues/files/11064402/log.zip)

**Comment by monfresh** [comment]
Hi @regiomag. I emailed you about 10 minutes ago. Can you check to see if you got it?

**Comment by monfresh** [comment]
For anyone else who might find this issue, the solution was to update the `nio4r` gem because version 1.2.1 doesn't work on Apple Silicon Macs. It was released in 2006, 4 years before Apple released the first M1 Mac. The latest version of `nio4r` does support Apple Silicon.

As I say, always make sure your gems are up to date if you can't install them. Updating gems fixes 99% of issues.
