### ISSUE TITLE
did not install

### ISSUE THREAD

**Issue by SaraGinsburg** [rubyonmac/rubyonmac-issues#3]
**In which version of Ruby on Mac did you find the bug?**
Basic, Plus, or Prime?Basic

**Describe the bug**
_**Rails is not currently installed on this system. To get the latest version, simply type:

    $ sudo gem install rails

You can then rerun your "rails" command.**_

**Details about your Mac**
Before you ran the script for the first time, did you already have development tools like Homebrew installed, or did you run it on a fresh and clean macOS? I had Homebrew

**Please attach the Ruby on Mac log file**
The log file will be called either `rom-basic.log`, or `rom-plus.log`, or `rom-prime.log`. You can find it in your Mac's Home folder.
[rom-basic.log](https://github.com/rubyonmac/rubyonmac-issues/files/8390335/rom-basic.log)

**Comment by monfresh** [comment]
Hi @SaraGinsburg , I just sent you an email, but I'll repeat it here for any others who might be wondering the same thing.

Thanks for buying Ruby on Mac.

The Basic version does not automatically install any gems. Only the Prime version does. 

The Basic version sets things up so that you are able to install gems, but it's up to you to install them manually.

Here's how you can install Rails:

1. Quit and restart Terminal
2. Verify you're using Ruby 3.1.1:
```
ruby -v
```

3. If it doesn't say 3.1.1, switch to it manually:

```
chruby 3.1.1
```

4. Install Rails:

```
gem install rails
```

5. Verify Rails is installed:

```
rails -v
```

**Comment by monfresh** [comment]
For anyone else seeing something similar, the issue was that this person had changed their Terminal preferences for "shells open with" from "Default login shell" to "Command".

When they first ran Ruby on Mac, it detected `zsh` as their shell, but then they switched to `bash`. The solution involved 2 steps:

1. Switch back to zsh:
```
chsh -s /bin/zsh
```

2. Set the Terminal preferences back to the default settings:
Here's a screenshot of what the "shells open with" preference should look like:
<img width="779" alt="Screen Shot 2022-04-01 at 11 54 40" src="https://user-images.githubusercontent.com/811150/161299042-35ad7bff-0355-43e0-9f9e-a04c7c3f4169.png">

Here's an article that might be helpful:
https://www.moncefbelyamani.com/which-shell-am-i-using-how-can-i-switch/
